"""Protocol Repository for any of the domain objects"""

from typing import Protocol, TypeVar
from uuid import UUID

DomainModel = TypeVar("DomainModel")
DBModel = TypeVar("DBModel")


class Repository[DomainModel, DBModel](Protocol):
    """A repository of objects T"""

    def create(self, model: DomainModel) -> DomainModel: ...
    def get(self, id: UUID) -> DomainModel | None: ...
    def update(self, model: DomainModel) -> DomainModel | None: ...
    def delete(self, id: UUID) -> DomainModel | None: ...
    def _to_db(self, model: DomainModel) -> DBModel: ...
    def _to_domain(self, db_entry: DBModel) -> DomainModel: ...
